// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authSessionsFieldNames          = builder.RawFieldNames(&AuthSessions{}, true)
	authSessionsRows                = strings.Join(authSessionsFieldNames, ",")
	authSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(authSessionsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	authSessionsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(authSessionsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	authSessionsModel interface {
		Insert(ctx context.Context, data *AuthSessions) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*AuthSessions, error)
		FindOneByTokenHash(ctx context.Context, tokenHash string) (*AuthSessions, error)
		Update(ctx context.Context, data *AuthSessions) error
		Delete(ctx context.Context, id string) error
	}

	defaultAuthSessionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuthSessions struct {
		Id         string       `db:"id"`
		UserId     string       `db:"user_id"`
		TokenHash  string       `db:"token_hash"`
		ExpiresAt  time.Time    `db:"expires_at"`
		RevokedAt  sql.NullTime `db:"revoked_at"`
		LastUsedAt sql.NullTime `db:"last_used_at"`
		CreatedAt  time.Time    `db:"created_at"`
	}
)

func newAuthSessionsModel(conn sqlx.SqlConn) *defaultAuthSessionsModel {
	return &defaultAuthSessionsModel{
		conn:  conn,
		table: `"public"."auth_sessions"`,
	}
}

func (m *defaultAuthSessionsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuthSessionsModel) FindOne(ctx context.Context, id string) (*AuthSessions, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", authSessionsRows, m.table)
	var resp AuthSessions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthSessionsModel) FindOneByTokenHash(ctx context.Context, tokenHash string) (*AuthSessions, error) {
	var resp AuthSessions
	query := fmt.Sprintf("select %s from %s where token_hash = $1 limit 1", authSessionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tokenHash)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthSessionsModel) Insert(ctx context.Context, data *AuthSessions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, authSessionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.TokenHash, data.ExpiresAt, data.RevokedAt, data.LastUsedAt)
	return ret, err
}

func (m *defaultAuthSessionsModel) Update(ctx context.Context, newData *AuthSessions) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, authSessionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.TokenHash, newData.ExpiresAt, newData.RevokedAt, newData.LastUsedAt)
	return err
}

func (m *defaultAuthSessionsModel) tableName() string {
	return m.table
}
