// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bookInvitesFieldNames          = builder.RawFieldNames(&BookInvites{}, true)
	bookInvitesRows                = strings.Join(bookInvitesFieldNames, ",")
	bookInvitesRowsExpectAutoSet   = strings.Join(stringx.Remove(bookInvitesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	bookInvitesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(bookInvitesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	bookInvitesModel interface {
		Insert(ctx context.Context, data *BookInvites) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*BookInvites, error)
		FindOneByInviteCode(ctx context.Context, inviteCode string) (*BookInvites, error)
		Update(ctx context.Context, data *BookInvites) error
		Delete(ctx context.Context, id string) error
	}

	defaultBookInvitesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BookInvites struct {
		Id              string         `db:"id"`
		BookId          string         `db:"book_id"`
		InviteCode      string         `db:"invite_code"`
		InviteLink      sql.NullString `db:"invite_link"`
		InvitedByUserId string         `db:"invited_by_user_id"`
		Role            string         `db:"role"`
		Status          string         `db:"status"`
		ExpiresAt       time.Time      `db:"expires_at"`
		CreatedAt       time.Time      `db:"created_at"`
		AcceptedAt      sql.NullTime   `db:"accepted_at"`
	}
)

func newBookInvitesModel(conn sqlx.SqlConn) *defaultBookInvitesModel {
	return &defaultBookInvitesModel{
		conn:  conn,
		table: `"public"."book_invites"`,
	}
}

func (m *defaultBookInvitesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBookInvitesModel) FindOne(ctx context.Context, id string) (*BookInvites, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", bookInvitesRows, m.table)
	var resp BookInvites
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBookInvitesModel) FindOneByInviteCode(ctx context.Context, inviteCode string) (*BookInvites, error) {
	var resp BookInvites
	query := fmt.Sprintf("select %s from %s where invite_code = $1 limit 1", bookInvitesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, inviteCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBookInvitesModel) Insert(ctx context.Context, data *BookInvites) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, bookInvitesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.BookId, data.InviteCode, data.InviteLink, data.InvitedByUserId, data.Role, data.Status, data.ExpiresAt, data.AcceptedAt)
	return ret, err
}

func (m *defaultBookInvitesModel) Update(ctx context.Context, newData *BookInvites) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, bookInvitesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.BookId, newData.InviteCode, newData.InviteLink, newData.InvitedByUserId, newData.Role, newData.Status, newData.ExpiresAt, newData.AcceptedAt)
	return err
}

func (m *defaultBookInvitesModel) tableName() string {
	return m.table
}
