// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	booksFieldNames          = builder.RawFieldNames(&Books{}, true)
	booksRows                = strings.Join(booksFieldNames, ",")
	booksRowsExpectAutoSet   = strings.Join(stringx.Remove(booksFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	booksRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(booksFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	booksModel interface {
		Insert(ctx context.Context, data *Books) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Books, error)
		Update(ctx context.Context, data *Books) error
		Delete(ctx context.Context, id string) error
	}

	defaultBooksModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Books struct {
		Id                  string         `db:"id"`
		Name                string         `db:"name"`
		Note                sql.NullString `db:"note"`
		DefaultCurrencyCode string         `db:"default_currency_code"`
		OwnerId             string         `db:"owner_id"`
		CreatedAt           time.Time      `db:"created_at"`
		UpdatedAt           time.Time      `db:"updated_at"`
		ArchivedAt          sql.NullTime   `db:"archived_at"`
	}
)

func newBooksModel(conn sqlx.SqlConn) *defaultBooksModel {
	return &defaultBooksModel{
		conn:  conn,
		table: `"public"."books"`,
	}
}

func (m *defaultBooksModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBooksModel) FindOne(ctx context.Context, id string) (*Books, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", booksRows, m.table)
	var resp Books
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBooksModel) Insert(ctx context.Context, data *Books) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, booksRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Note, data.DefaultCurrencyCode, data.OwnerId, data.ArchivedAt)
	return ret, err
}

func (m *defaultBooksModel) Update(ctx context.Context, data *Books) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, booksRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Note, data.DefaultCurrencyCode, data.OwnerId, data.ArchivedAt)
	return err
}

func (m *defaultBooksModel) tableName() string {
	return m.table
}
