// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bookMembersFieldNames          = builder.RawFieldNames(&BookMembers{}, true)
	bookMembersRows                = strings.Join(bookMembersFieldNames, ",")
	bookMembersRowsExpectAutoSet   = strings.Join(stringx.Remove(bookMembersFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	bookMembersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(bookMembersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	bookMembersModel interface {
		Insert(ctx context.Context, data *BookMembers) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*BookMembers, error)
		FindOneByBookIdUserId(ctx context.Context, bookId string, userId string) (*BookMembers, error)
		Update(ctx context.Context, data *BookMembers) error
		Delete(ctx context.Context, id string) error
	}

	defaultBookMembersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BookMembers struct {
		Id       string    `db:"id"`
		BookId   string    `db:"book_id"`
		UserId   string    `db:"user_id"`
		Role     string    `db:"role"`
		JoinedAt time.Time `db:"joined_at"`
	}
)

func newBookMembersModel(conn sqlx.SqlConn) *defaultBookMembersModel {
	return &defaultBookMembersModel{
		conn:  conn,
		table: `"public"."book_members"`,
	}
}

func (m *defaultBookMembersModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBookMembersModel) FindOne(ctx context.Context, id string) (*BookMembers, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", bookMembersRows, m.table)
	var resp BookMembers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBookMembersModel) FindOneByBookIdUserId(ctx context.Context, bookId string, userId string) (*BookMembers, error) {
	var resp BookMembers
	query := fmt.Sprintf("select %s from %s where book_id = $1 and user_id = $2 limit 1", bookMembersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, bookId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBookMembersModel) Insert(ctx context.Context, data *BookMembers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, bookMembersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.BookId, data.UserId, data.Role, data.JoinedAt)
	return ret, err
}

func (m *defaultBookMembersModel) Update(ctx context.Context, newData *BookMembers) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, bookMembersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.BookId, newData.UserId, newData.Role, newData.JoinedAt)
	return err
}

func (m *defaultBookMembersModel) tableName() string {
	return m.table
}
