// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ledgerTransactionsFieldNames          = builder.RawFieldNames(&LedgerTransactions{}, true)
	ledgerTransactionsRows                = strings.Join(ledgerTransactionsFieldNames, ",")
	ledgerTransactionsRowsExpectAutoSet   = strings.Join(stringx.Remove(ledgerTransactionsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	ledgerTransactionsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(ledgerTransactionsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	ledgerTransactionsModel interface {
		Insert(ctx context.Context, data *LedgerTransactions) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*LedgerTransactions, error)
		Update(ctx context.Context, data *LedgerTransactions) error
		Delete(ctx context.Context, id string) error
	}

	defaultLedgerTransactionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LedgerTransactions struct {
		Id               string         `db:"id"`
		BookId           string         `db:"book_id"`
		Type             string         `db:"type"`
		AmountMinor      int64          `db:"amount_minor"`
		CurrencyCode     string         `db:"currency_code"`
		CategoryLevel1Id string         `db:"category_level1_id"`
		CategoryLevel2Id string         `db:"category_level2_id"`
		OccurredAt       time.Time      `db:"occurred_at"`
		Note             sql.NullString `db:"note"`
		CreatedBy        string         `db:"created_by"`
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        time.Time      `db:"updated_at"`
		DeletedAt        sql.NullTime   `db:"deleted_at"`
	}
)

func newLedgerTransactionsModel(conn sqlx.SqlConn) *defaultLedgerTransactionsModel {
	return &defaultLedgerTransactionsModel{
		conn:  conn,
		table: `"public"."ledger_transactions"`,
	}
}

func (m *defaultLedgerTransactionsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLedgerTransactionsModel) FindOne(ctx context.Context, id string) (*LedgerTransactions, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", ledgerTransactionsRows, m.table)
	var resp LedgerTransactions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLedgerTransactionsModel) Insert(ctx context.Context, data *LedgerTransactions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)", m.table, ledgerTransactionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.BookId, data.Type, data.AmountMinor, data.CurrencyCode, data.CategoryLevel1Id, data.CategoryLevel2Id, data.OccurredAt, data.Note, data.CreatedBy, data.DeletedAt)
	return ret, err
}

func (m *defaultLedgerTransactionsModel) Update(ctx context.Context, data *LedgerTransactions) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, ledgerTransactionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.BookId, data.Type, data.AmountMinor, data.CurrencyCode, data.CategoryLevel1Id, data.CategoryLevel2Id, data.OccurredAt, data.Note, data.CreatedBy, data.DeletedAt)
	return err
}

func (m *defaultLedgerTransactionsModel) tableName() string {
	return m.table
}
