// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	transactionCategoriesFieldNames          = builder.RawFieldNames(&TransactionCategories{}, true)
	transactionCategoriesRows                = strings.Join(transactionCategoriesFieldNames, ",")
	transactionCategoriesRowsExpectAutoSet   = strings.Join(stringx.Remove(transactionCategoriesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	transactionCategoriesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(transactionCategoriesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	transactionCategoriesModel interface {
		Insert(ctx context.Context, data *TransactionCategories) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*TransactionCategories, error)
		FindOneByIdBookIdType(ctx context.Context, id string, bookId string, tp string) (*TransactionCategories, error)
		Update(ctx context.Context, data *TransactionCategories) error
		Delete(ctx context.Context, id string) error
	}

	defaultTransactionCategoriesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TransactionCategories struct {
		Id         string         `db:"id"`
		BookId     string         `db:"book_id"`
		Name       string         `db:"name"`
		Type       string         `db:"type"`
		Level      string         `db:"level"`
		ParentId   sql.NullString `db:"parent_id"`
		Icon       sql.NullString `db:"icon"`
		ColorHex   sql.NullString `db:"color_hex"`
		SortOrder  int            `db:"sort_order"`
		IsArchived bool           `db:"is_archived"`
		CreatedAt  time.Time      `db:"created_at"`
		UpdatedAt  time.Time      `db:"updated_at"`
	}
)

func newTransactionCategoriesModel(conn sqlx.SqlConn) *defaultTransactionCategoriesModel {
	return &defaultTransactionCategoriesModel{
		conn:  conn,
		table: `"public"."transaction_categories"`,
	}
}

func (m *defaultTransactionCategoriesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTransactionCategoriesModel) FindOne(ctx context.Context, id string) (*TransactionCategories, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", transactionCategoriesRows, m.table)
	var resp TransactionCategories
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransactionCategoriesModel) FindOneByIdBookIdType(ctx context.Context, id string, bookId string, tp string) (*TransactionCategories, error) {
	var resp TransactionCategories
	query := fmt.Sprintf("select %s from %s where id = $1 and book_id = $2 and type = $3 limit 1", transactionCategoriesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, bookId, tp)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransactionCategoriesModel) Insert(ctx context.Context, data *TransactionCategories) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, transactionCategoriesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.BookId, data.Name, data.Type, data.Level, data.ParentId, data.Icon, data.ColorHex, data.SortOrder, data.IsArchived)
	return ret, err
}

func (m *defaultTransactionCategoriesModel) Update(ctx context.Context, newData *TransactionCategories) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, transactionCategoriesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.BookId, newData.Name, newData.Type, newData.Level, newData.ParentId, newData.Icon, newData.ColorHex, newData.SortOrder, newData.IsArchived)
	return err
}

func (m *defaultTransactionCategoriesModel) tableName() string {
	return m.table
}
