// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

type RegisterReq struct {
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type UserResp struct {
	Data User `json:"data"`
}
