// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BookListResp struct {
	Data []Book `json:"data"`
}

type BookPathReq struct {
	BookId string `path:"bookId"`
}

type BookResp struct {
	Data Book `json:"data"`
}

type CreateBookReq struct {
	Name                string `json:"name"`
	Note                string `json:"note,optional"`
	DefaultCurrencyCode string `json:"defaultCurrencyCode"`
}

type UpdateBookReq struct {
	BookId              string `path:"bookId"`
	Name                string `json:"name"`
	Note                string `json:"note,optional"`
	DefaultCurrencyCode string `json:"defaultCurrencyCode"`
}
