// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CategoryPathReq struct {
	BookId     string `path:"bookId"`
	CategoryId string `path:"categoryId"`
}

type CreateCategoryReq struct {
	BookId   string `path:"bookId"`
	Name     string `json:"name"`
	Type     string `json:"type,optional"`
	Level    string `json:"level"`
	ParentId string `json:"parentId,optional"`
	Icon     string `json:"icon,optional"`
	ColorHex string `json:"colorHex,optional"`
}

type ListCategoriesReq struct {
	BookId          string `path:"bookId"`
	Type            string `form:"type,optional"`
	IncludeArchived bool   `form:"includeArchived,optional"`
}

type TransactionCategoryListResp struct {
	Data []TransactionCategory `json:"data"`
}

type TransactionCategoryResp struct {
	Data TransactionCategory `json:"data"`
}

type UpdateCategoryReq struct {
	BookId     string `path:"bookId"`
	CategoryId string `path:"categoryId"`
	Name       string `json:"name"`
	Type       string `json:"type"`
	Level      string `json:"level"`
	ParentId   string `json:"parentId,optional"`
	Icon       string `json:"icon,optional"`
	ColorHex   string `json:"colorHex,optional"`
	SortOrder  int    `json:"sortOrder"`
	IsArchived bool   `json:"isArchived"`
}
