// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AcceptInviteReq struct {
	InviteCode string `path:"inviteCode"`
}

type BookInviteListResp struct {
	Data []BookInvite `json:"data"`
}

type BookInviteResp struct {
	Data BookInvite `json:"data"`
}

type CreateInviteReq struct {
	BookId string `path:"bookId"`
	Role   string `json:"role"`
}

type ListInvitesReq struct {
	BookId string `path:"bookId"`
}

type RevokeInviteReq struct {
	BookId   string `path:"bookId"`
	InviteId string `path:"inviteId"`
}
