// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BookMemberListResp struct {
	Data []BookMember `json:"data"`
}

type BookMembersReq struct {
	BookId string `path:"bookId"`
}

type RemoveMemberReq struct {
	BookId   string `path:"bookId"`
	MemberId string `path:"memberId"`
}

type UpdateMemberRoleReq struct {
	BookId   string `path:"bookId"`
	MemberId string `path:"memberId"`
	Role     string `json:"role"`
}
