// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BookStatisticsReq struct {
	BookId string `path:"bookId"`
}

type CategoryRatioSliceListResp struct {
	Data []CategoryRatioSlice `json:"data"`
}

type LedgerSummaryResp struct {
	Data LedgerSummary `json:"data"`
}

type StatisticsCategoriesReq struct {
	BookId     string `path:"bookId"`
	Scope      string `form:"scope"`
	Type       string `form:"type"`
	Level      string `form:"level"`
	RelativeTo string `form:"relativeTo,optional"`
}

type StatisticsScopeReq struct {
	BookId     string `path:"bookId"`
	Scope      string `form:"scope"`
	RelativeTo string `form:"relativeTo,optional"`
}

type StatisticsSnapshotResp struct {
	Data StatisticsSnapshot `json:"data"`
}

type TrendPointListResp struct {
	Data []TrendPoint `json:"data"`
}
