// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateTransactionReq struct {
	BookId           string `path:"bookId"`
	Type             string `json:"type"`
	AmountMinor      int64  `json:"amountMinor"`
	CurrencyCode     string `json:"currencyCode"`
	CategoryLevel1Id string `json:"categoryLevel1Id"`
	CategoryLevel2Id string `json:"categoryLevel2Id"`
	OccurredAt       string `json:"occurredAt"`
	Note             string `json:"note,optional"`
}

type LedgerTransactionListResp struct {
	Data []LedgerTransaction `json:"data"`
}

type LedgerTransactionResp struct {
	Data LedgerTransaction `json:"data"`
}

type ListTransactionsReq struct {
	BookId string `path:"bookId"`
	From   string `form:"from,optional"`
	To     string `form:"to,optional"`
}

type TransactionPathReq struct {
	BookId        string `path:"bookId"`
	TransactionId string `path:"transactionId"`
}

type UpdateTransactionReq struct {
	BookId           string `path:"bookId"`
	TransactionId    string `path:"transactionId"`
	Type             string `json:"type"`
	AmountMinor      int64  `json:"amountMinor"`
	CurrencyCode     string `json:"currencyCode"`
	CategoryLevel1Id string `json:"categoryLevel1Id"`
	CategoryLevel2Id string `json:"categoryLevel2Id"`
	OccurredAt       string `json:"occurredAt"`
	Note             string `json:"note,optional"`
}
