// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Book struct {
	Id                  string `json:"id"`
	Name                string `json:"name"`
	Note                string `json:"note,optional"`
	DefaultCurrencyCode string `json:"defaultCurrencyCode"`
	OwnerId             string `json:"ownerId"`
	CreatedAt           string `json:"createdAt"`
	UpdatedAt           string `json:"updatedAt"`
	ArchivedAt          string `json:"archivedAt,optional"`
}

type BookInvite struct {
	Id              string `json:"id"`
	BookId          string `json:"bookId"`
	InviteCode      string `json:"inviteCode"`
	InviteLink      string `json:"inviteLink,optional"`
	InvitedByUserId string `json:"invitedByUserId"`
	Role            string `json:"role"`
	Status          string `json:"status"`
	ExpiresAt       string `json:"expiresAt"`
	CreatedAt       string `json:"createdAt"`
	AcceptedAt      string `json:"acceptedAt,optional"`
}

type BookMember struct {
	Id       string `json:"id"`
	BookId   string `json:"bookId"`
	UserId   string `json:"userId"`
	Role     string `json:"role"`
	JoinedAt string `json:"joinedAt"`
}

type BookMemberResp struct {
	Data BookMember `json:"data"`
}

type CategoryRatioSlice struct {
	Id           string  `json:"id"`
	CategoryId   string  `json:"categoryId"`
	CategoryName string  `json:"categoryName"`
	AmountMinor  int64   `json:"amountMinor"`
	Percentage   float64 `json:"percentage"`
}

type EmptyResp struct {
}

type LedgerSummary struct {
	TotalIncomeMinor  int64  `json:"totalIncomeMinor"`
	TotalExpenseMinor int64  `json:"totalExpenseMinor"`
	BalanceMinor      int64  `json:"balanceMinor"`
	CurrencyCode      string `json:"currencyCode"`
}

type LedgerTransaction struct {
	Id               string `json:"id"`
	BookId           string `json:"bookId"`
	Type             string `json:"type"`
	AmountMinor      int64  `json:"amountMinor"`
	CurrencyCode     string `json:"currencyCode"`
	CategoryLevel1Id string `json:"categoryLevel1Id"`
	CategoryLevel2Id string `json:"categoryLevel2Id"`
	OccurredAt       string `json:"occurredAt"`
	Note             string `json:"note,optional"`
	CreatedBy        string `json:"createdBy"`
	CreatedAt        string `json:"createdAt"`
	UpdatedAt        string `json:"updatedAt"`
	DeletedAt        string `json:"deletedAt,optional"`
}

type PercentageDelta struct {
	Kind  string  `json:"kind"`
	Value float64 `json:"value,optional"`
}

type StatisticsSnapshot struct {
	Scope                    string          `json:"scope"`
	TotalIncomeMinor         int64           `json:"totalIncomeMinor"`
	IncomeDelta              PercentageDelta `json:"incomeDelta"`
	TotalExpenseMinor        int64           `json:"totalExpenseMinor"`
	ExpenseDelta             PercentageDelta `json:"expenseDelta"`
	NetAssetMinor            int64           `json:"netAssetMinor"`
	AverageDailyIncomeMinor  int64           `json:"averageDailyIncomeMinor"`
	AverageDailyIncomeDelta  PercentageDelta `json:"averageDailyIncomeDelta"`
	AverageDailyExpenseMinor int64           `json:"averageDailyExpenseMinor"`
	AverageDailyExpenseDelta PercentageDelta `json:"averageDailyExpenseDelta"`
	CurrencyCode             string          `json:"currencyCode"`
}

type TransactionCategory struct {
	Id         string `json:"id"`
	BookId     string `json:"bookId"`
	Name       string `json:"name"`
	Type       string `json:"type"`
	Level      string `json:"level"`
	ParentId   string `json:"parentId,optional"`
	Icon       string `json:"icon,optional"`
	ColorHex   string `json:"colorHex,optional"`
	SortOrder  int    `json:"sortOrder"`
	IsArchived bool   `json:"isArchived"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type TrendPoint struct {
	Id           string `json:"id"`
	Date         string `json:"date"`
	IncomeMinor  int64  `json:"incomeMinor"`
	ExpenseMinor int64  `json:"expenseMinor"`
}

type User struct {
	Id        string `json:"id"`
	Nickname  string `json:"nickname"`
	AvatarURL string `json:"avatarURL,optional"`
	Email     string `json:"email,optional"`
	Phone     string `json:"phone,optional"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
